version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: "uno-app"
    command: ["sh", "-c", "sleep 5 && python app.py"]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis

volumes:
  redis_data:
