name: createPullRequest
on:
  push:
    branches: "*"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get current branch name
        id: get-branch
        run: echo "Current branch is ${{ github.ref_name }}"
        shell: bash

      - name: Check if PR already exists (optional)
        id: check-pr-exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          current_branch="${{ github.ref_name }}"
          prs=$(gh pr list -B targetBranch -H sourceBranch)  
          echo Size of PRS ARRAY: ${#prs[@]}
          echo Length of PRS[0] string: ${#prs[0]}
          
          if ((${#prs[@]} > 0 && ${#prs[0]} != 0 )); then
            echo skipping PR creation
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
